"""
AI Health Twin — anomaly scoring.

Uses a real scikit-learn IsolationForest, trained on residual/vibration
features generated by running the telemetry simulator in NORMAL_CRUISE
(i.e. "what does healthy look like"). This is genuine unsupervised
anomaly detection, not a hard-coded score — but it is trained on
synthetic data, which is stated explicitly wherever this score is shown.

Feature vector per frame: [cht_residual_c, egt_residual_c,
vibration_excess_mms, fuel_flow_residual_lph]. vibration_excess is
vibration minus the RPM-dependent healthy baseline, computed the same
way the simulator computes its own baseline, so the detector reasons
about "vibration beyond what this RPM would explain".
"""
from __future__ import annotations

import numpy as np
from sklearn.ensemble import IsolationForest

from schemas.telemetry import ScenarioName
from telemetry.simulator import EngineSimulator
from physics.residuals import compute_residuals


def _healthy_baseline_vibration(rpm: float) -> float:
    rpm_frac = max(0.0, min(1.0, (rpm - 1700.0) / (5500.0 - 1700.0)))
    return 1.0 + 2.5 * rpm_frac


def _build_training_features(n_samples: int = 900, seed: int = 7) -> np.ndarray:
    sim = EngineSimulator(scenario=ScenarioName.NORMAL_CRUISE, seed=seed)
    rows = []
    for _ in range(n_samples):
        frame = sim.step(dt_seconds=1.0)
        residuals = compute_residuals(frame)
        vib_excess = frame.vibration_mms - _healthy_baseline_vibration(frame.rpm)
        rows.append([
            residuals.cht_residual_c,
            residuals.egt_residual_c,
            vib_excess,
            residuals.fuel_flow_residual_lph,
        ])
    return np.array(rows)


class AnomalyDetector:
    """One instance is trained once at process startup and reused across
    all incoming frames — retraining per-request would be both slow and
    meaningless (it would just relearn "current data is normal")."""

    FEATURE_NAMES = ["CHT residual", "EGT residual", "Vibration (excess)", "Fuel flow residual"]

    def __init__(self, n_training_samples: int = 900):
        training_features = _build_training_features(n_training_samples)
        self._scale = np.maximum(np.std(training_features, axis=0), 1e-6)
        self._model = IsolationForest(
            n_estimators=150,
            contamination=0.03,
            random_state=42,
        )
        self._model.fit(training_features / self._scale)

    def score(self, cht_residual_c: float, egt_residual_c: float, vibration_mms: float,
              fuel_flow_residual_lph: float, rpm: float) -> tuple[float, list[str]]:
        """Returns (anomaly_score, top_contributing_feature_names).
        anomaly_score is rescaled so that ~0 = typical healthy operation
        and larger positive values = more anomalous (opposite sign
        convention to sklearn's raw decision_function, inverted here so
        the rest of the app doesn't need to know sklearn's convention)."""
        vib_excess = vibration_mms - _healthy_baseline_vibration(rpm)
        raw = np.array([[cht_residual_c, egt_residual_c, vib_excess, fuel_flow_residual_lph]])
        scaled = raw / self._scale

        # decision_function: higher = more normal in sklearn's convention.
        # IsolationForest's decision_function has a fairly narrow dynamic
        # range in practice, so we rescale it onto a more display-friendly
        # 0-ish (healthy) to double-digits (extreme) range. The constant
        # here is a display calibration, not a statistical guarantee —
        # what matters is that it preserves the model's relative ordering.
        normality = self._model.decision_function(scaled)[0]
        anomaly_score = float(max(0.0, -normality * 30.0))

        # Which standardized feature contributed most to this being unusual.
        abs_scaled = np.abs(scaled[0])
        top_idx = np.argsort(-abs_scaled)[:2]
        top_features = [self.FEATURE_NAMES[i] for i in top_idx if abs_scaled[i] > 1.0]

        return anomaly_score, top_features
